version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next
    versions:
    - 10.0.9
    - 10.1.1
  - dependency-name: framer-motion
    versions:
    - 4.0.3
